### ISSUE TITLE
Problem with configuration

### ISSUE THREAD

**Issue by AlessiaPileri** [clevertech/email-service#4]
Hi,
I have an issue with the configuration as an express router. I have all configurations in .env file but when I start the router I have following message:
error: No valid TRANSPORT set
error: TypeError: Cannot set property 'mailer' of undefined
It seems as it can't read configuration.
These are my env variables:
AWS_KEY=''
AWS_SECRET='********'
AWS_REGION=''
TEMPLATES_DIR='/my/local/path'
TRANSPORT='ses'
DEFAULT_FROM='info@smartsix.it'
DEFAULT_LANGUAGE='en'

And this is my code to start the service:
```
import emailService from 'pnp-email-service';

export default function (app) {

const router = emailService.createRouter();

app.use('/api/email', router);

return router;
}
```

Thank you

Alessia

**Comment by AlessiaPileri** [comment]
Yes, I add the console.log you suggested, the output is:

transport: ses

as expected, but the package doesn't read it

**Comment by gimenete** [comment]
Using `pnp-email-service: ^0.1.7`, this code works fine:

```javascript
const emailService = require('pnp-email-service')
console.log('transport', process.env.TRANSPORT)
const router = emailService.createRouter()
```

Invoking it with `TRANSPORT=ses node index.js`

Can you check you have the latest version? If so, can you create a minimal project to replicate the problem?

**Comment by AlessiaPileri** [comment]
I think the problem is that I'm using babel to write code in ES6 syntax,
because if I write a simple project without babel, it works!
Debugging the package source code, the problem seems to be in in Array.find
that return always -1 when it tries to get configuration options in .env
file or config object.

2017-10-19 18:18 GMT+02:00 Alberto Gimeno <notifications@github.com>:

**Comment by gimenete** [comment]
It is possible that babel is transpiling `process.env` in your code in some way, but it's not doing it in the package code.

An alternative to env variables is to pass values in the `emailService.createRouter()` call. Example:

```
emailService.createRouter({ TRANSPORT: 'ses' })
// or
emailService.createRouter({ TRANSPORT: process.env.TRANSPORT })
```

Can you try with that?

**Comment by AlessiaPileri** [comment]
I found the problem: in my project I'm using a package to export data in excel and now I see that package redefines some prototype methods of Array object!!!
If I delete that package, all works fine.
Thanks for your help @gimenete

**Comment by gimenete** [comment]
Awesome @AlessiaPileri :)
